spring:
  application:
    name: account-service
  datasource:
    url: jdbc:postgresql://dpg-coc136779t8c73febbeg-a.oregon-postgres.render.com:5432/password_manager_devathon
    username: password_manager_devathon_user
    password: dsy48OOseQPuzgDlAqYvkg30H79X1F4r
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  flyway:
    baseline-on-migrate: true
server:
  error:
    include-stacktrace: never


